[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token 2022 Integration Tests"
edition = "2021"
license = "Apache-2.0"
name = "spl-token-2022-test"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.0.1"

[features]
test-sbf = ["zk-ops"]
default = ["zk-ops"]
zk-ops = []

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = "0.1"
borsh = "1.5.1"
futures-util = "0.3"
solana-program = ">=1.18.11,<=2"
solana-program-test = ">=1.18.11,<=2"
solana-sdk = ">=1.18.11,<=2"
spl-associated-token-account = { version = "3.0.2", path = "../../associated-token-account/program" }
spl-memo = { version = "4.0.1", path = "../../memo/program", features = [
  "no-entrypoint",
] }
spl-pod = { version = "0.2.2", path = "../../libraries/pod" }
spl-token-2022 = { version = "3.0.2", path = "../program-2022", features = [
  "no-entrypoint",
] }
spl-instruction-padding = { version = "0.1.1", path = "../../instruction-padding/program", features = [
  "no-entrypoint",
] }
spl-tlv-account-resolution = { version = "0.6.3", path = "../../libraries/tlv-account-resolution" }
spl-token-client = { version = "0.10.0", path = "../client" }
spl-token-group-interface = { version = "0.2.3", path = "../../token-group/interface" }
spl-token-metadata-interface = { version = "0.3.3", path = "../../token-metadata/interface" }
spl-transfer-hook-example = { version = "0.6", path = "../transfer-hook/example", features = [
  "no-entrypoint",
] }
spl-transfer-hook-interface = { version = "0.6.3", path = "../transfer-hook/interface" }
test-case = "3.3"
