name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JS_PACKAGES: "['js', 'js-legacy']"
  SBPF_PROGRAM_PACKAGES: "['confidential-elgamal-registry', 'program']"
  RUST_PACKAGES: "['clients-cli', 'clients-rust-legacy', 'interface', 'program', 'confidential-ciphertext-arithmetic', 'confidential-elgamal-registry', 'confidential-proof-extraction', 'confidential-proof-generation', 'confidential-proof-tests']"
  WASM_PACKAGES: "['interface', 'program']"

jobs:
  set_env:
    name: Set variables to be used in strategy definitions in reusable workflow
    runs-on: ubuntu-latest
    outputs:
      RUST_TOOLCHAIN_NIGHTLY: ${{ steps.compute.outputs.RUST_TOOLCHAIN_NIGHTLY }}
      SOLANA_CLI_VERSION: ${{ steps.compute.outputs.SOLANA_CLI_VERSION }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Compute variables
        id: compute
        shell: bash
        run: |
          echo "RUST_TOOLCHAIN_NIGHTLY=$(make rust-toolchain-nightly)" >> "$GITHUB_OUTPUT"
          echo "SOLANA_CLI_VERSION=$(make solana-cli-version)" >> "$GITHUB_OUTPUT"

  main:
    uses: joncinque/actions/.github/workflows/main.yml@reuse-main
    with:
      js-packages: ${{ env.JS_PACKAGES }}
      sbpf-program-packages: ${{ env.SBPF_PROGRAM_PACKAGES }}
      rust-packages: ${{ env.RUST_PACKAGES }}
      wasm-packages: ${{ env.WASM_PACKAGES }}
      rust-toolchain-nightly: ${{ needs.set_env.outputs.RUST_TOOLCHAIN_NIGHTLY }}
      solana-cli-version: ${{ needs.set_env.outputs.SOLANA_CLI_VERSION }}
